baseURL = ""
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "Azrea Amis"
theme = "hugo-xmin"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[taxonomies]
tag = "tags"
project = "projects"

[params]
    footer = "&copy; [Azrea Amis](http://atamis.me) --- [Github](http://github.com/atamis) --- 2020"
    custom_css = ["/css/syntax.css", "/css/custom.css", "/css/pride_helper.css"]

[permalinks]
    posts = "/posts/:year/:month/:day/:slug/"
    notes = "/notes/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

[[menu.main]]
    name = "Pictures"
    url = "/pictures/"
    weight = 5

[[menu.main]]
    name = "Resume"
    url = "/downloads/resume.pdf"
    weight = 6
