baseURL = "http://atamis.me/"
languageCode = "en-us"
title = "Andrew Amis"
theme = "hugo-xmin"

[params]
    footer = "&copy; [Andrew Amis](http://atamis.me) --- [Github](http://github.com/atams) --- 2018"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

[[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 3

[[menu.main]]
    name = "Pictures"
    url = "/pictures/"
    weight = 4

[[menu.main]]
    name = "Resume"
    url = "/downloads/resume.pdf"
    weight = 5
