name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git submodule update --init --recursive

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: atamis/atamis.me/atamis-me
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        snapshot: true

    # - name: Publish to Ava Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: atamis.me
    #     username: ${{ secrets.AVA_DOCKER_USERNAME }}
    #     password: ${{ secrets.AVA_DOCKER_PASSWORD }}
    #     registry: reg.ava.azrea.me
    #     snapshot: true
